# example netlify.toml

[build]
    command = "vite build"
    functions = "netlify/functions"
    publish = "dist"

## Uncomment to use this redirect for single page applications
## Not needed for statit cile generators

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200    
##    headers = { Access-Control-Allow-Origin = "*"}

##[[headers]]
##  # Define which paths this specific [[headers]] block will cover.
##  for = "/*"
##    [headers.values]
##    Access-Control-Allow-Origin = "*"    



    